# version: '1.0.0'

services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret

  server-auth:
    build: ./auth
    ports:
      - 3001:3001
    volumes:
      - ./auth:/app
      - /app/node_modules
    env_file:
      - ./auth/config/.env
    depends_on:
      - mongodb

  nft-service:
    build:
      context: ./nft
    container_name: nft-service
    ports:
      - "3002:3002"
    env_file:
      - ./nft/config/.env
    volumes:
      - ./nft:/app
      - /app/node_modules
    depends_on:
      - mongodb


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8002:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_URL: mongodb://mongoadmin:secret@mongodb:27017/


volumes:
  data:
